# Generated by Django 4.2.16 on 2024-11-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstatus',
            options={'verbose_name': 'Client Status', 'verbose_name_plural': 'Client Statuses'},
        ),
    ]
