# Generated by Django 4.2.16 on 2024-11-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_alter_clientstatus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('enrollment_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='customers_photos/')),
                ('how_did_you_hear_details', models.TextField(blank=True, null=True)),
                ('has_illness', models.BooleanField(default=False, verbose_name='Padece algún tipo de enfermedad?')),
                ('has_allergy', models.BooleanField(default=False, verbose_name='Padece alguna alergia?')),
                ('has_flat_feet', models.BooleanField(default=False, verbose_name='Tiene pie plano?')),
                ('has_heart_conditions', models.BooleanField(default=False, verbose_name='Tiene problemas cardiacos?')),
                ('how_did_you_hear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sources', to='catalogs.discoverysource')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='customers', to='catalogs.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='customers.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_statuses', to='catalogs.clientstatus')),
            ],
            options={
                'unique_together': {('customer', 'status', 'date_changed')},
            },
        ),
    ]
